development:
  # AWS SES
  SES_USERNAME: YOUR_USERNAME
  SES_PASSWORD: YOUR_PASSWORD
  FROM_EMAIL:   VERIFIED_FROM_EMAIL
  TO_EMAIL:     VERIFIED_TO_EMAIL

test:
  # AWS SES
  SES_USERNAME: YOUR_USERNAME
  SES_PASSWORD: YOUR_PASSWORD
  FROM_EMAIL:   VERIFIED_FROM_EMAIL
  TO_EMAIL:     VERIFIED_TO_EMAIL
